default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: chicagofood_development

test:
  <<: *default
  database: chicagofood_test

production:
  <<: *default
  database: chicagofood_production
