development:
  adapter: postgresql
  encoding: unicode
  database: chicagofood_development
  pool: 5
  username: rsefer
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: chicagofood_test
  pool: 5
  username: rsefer
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: chicagofood_production
  pool: 5
  username: chicagofood
  password: